ReversiWpf: ReversiWpf.SettingWindow Class Reference
ReversiWpf.SettingWindow Class Reference
SettingWindow
Public Member Functions
void InitializeComponent ()
InitializeComponent
void InitializeComponent ()
InitializeComponent
void InitializeComponent ()
InitializeComponent
void InitializeComponent ()
InitializeComponent
SettingWindow (ReversiSetting mSetting)
コンストラクタ
Properties
ReversiSetting mSetting [get, set]
Private Member Functions
void System.Windows.Markup.IComponentConnector. Connect (int connectionId, object target)
void System.Windows.Markup.IComponentConnector. Connect (int connectionId, object target)
void System.Windows.Markup.IComponentConnector. Connect (int connectionId, object target)
void System.Windows.Markup.IComponentConnector. Connect (int connectionId, object target)
void reflectSettingForm ()
フォームに設定を反映
void loadSettingForm ()
void pictureBoxPlayerColor1_MouseLeftButtonDown (object sender, MouseButtonEventArgs e)
プレイヤー1の色クリック
void pictureBoxPlayerColor2_MouseLeftButtonDown (object sender, MouseButtonEventArgs e)
プレイヤー2の色クリック
void pictureBoxBackGroundColor_MouseLeftButtonDown (object sender, MouseButtonEventArgs e)
背景の色クリック
void pictureBoxBorderColor_MouseLeftButtonDown (object sender, MouseButtonEventArgs e)
枠線の色クリック
void buttonDefault_Click (object sender, RoutedEventArgs e)
デフォルト設定に戻すボタンクリック
void buttonSave_Click (object sender, RoutedEventArgs e)
保存ボタンクリック
void buttonCancel_Click (object sender, RoutedEventArgs e)
キャンセルボタンクリック
Private Attributes
bool _contentLoaded
ReversiSetting _mSetting
リバーシ設定クラス
Detailed Description
SettingWindow
SettingWindow.xaml の相互作用ロジッククラス
Definition at line 41 of file SettingWindow.g.cs.
Constructor & Destructor Documentation
SettingWindow()
ReversiWpf.SettingWindow.SettingWindow (ReversiSetting mSetting)
コンストラクタ
Returns
ありません
Author
Yuta Yoshinaga
Date
2017.10.20
Definition at line 61 of file SettingWindow.xaml.cs.
Member Function Documentation
buttonCancel_Click()
void ReversiWpf.SettingWindow.buttonCancel_Click (object sender, RoutedEventArgs e) private
キャンセルボタンクリック
Parameters
[in] object sender
[in] RoutedEventArgs e
Returns
ありません
Author
Yuta Yoshinaga
Date
2017.10.20
Definition at line 478 of file SettingWindow.xaml.cs.
Referenced by ReversiWpf.SettingWindow.InitializeComponent().
buttonDefault_Click()
void ReversiWpf.SettingWindow.buttonDefault_Click (object sender, RoutedEventArgs e) private
デフォルト設定に戻すボタンクリック
Parameters
[in] object sender
[in] RoutedEventArgs e
Returns
ありません
Author
Yuta Yoshinaga
Date
2017.10.20
Definition at line 446 of file SettingWindow.xaml.cs.
Referenced by ReversiWpf.SettingWindow.InitializeComponent().
buttonSave_Click()
void ReversiWpf.SettingWindow.buttonSave_Click (object sender, RoutedEventArgs e) private
保存ボタンクリック
Parameters
[in] object sender
[in] RoutedEventArgs e
Returns
ありません
Author
Yuta Yoshinaga
Date
2017.10.20
Definition at line 462 of file SettingWindow.xaml.cs.
Referenced by ReversiWpf.SettingWindow.InitializeComponent().
InitializeComponent() [1/4]
void ReversiWpf.SettingWindow.InitializeComponent ()
InitializeComponent
Definition at line 282 of file SettingWindow.g.i.cs.
InitializeComponent() [2/4]
void ReversiWpf.SettingWindow.InitializeComponent ()
InitializeComponent
Definition at line 282 of file SettingWindow.g.cs.
Referenced by ReversiWpf.SettingWindow.SettingWindow().
InitializeComponent() [3/4]
void ReversiWpf.SettingWindow.InitializeComponent ()
InitializeComponent
Definition at line 282 of file SettingWindow.g.cs.
InitializeComponent() [4/4]
void ReversiWpf.SettingWindow.InitializeComponent ()
InitializeComponent
Definition at line 282 of file SettingWindow.g.i.cs.
pictureBoxBackGroundColor_MouseLeftButtonDown()
void ReversiWpf.SettingWindow.pictureBoxBackGroundColor_MouseLeftButtonDown (object sender, MouseButtonEventArgs e) private
背景の色クリック
Parameters
[in] object sender
[in] MouseButtonEventArgs e
Returns
ありません
Author
Yuta Yoshinaga
Date
2017.10.20
Definition at line 396 of file SettingWindow.xaml.cs.
Referenced by ReversiWpf.SettingWindow.InitializeComponent().
pictureBoxBorderColor_MouseLeftButtonDown()
void ReversiWpf.SettingWindow.pictureBoxBorderColor_MouseLeftButtonDown (object sender, MouseButtonEventArgs e) private
枠線の色クリック
Parameters
[in] object sender
[in] MouseButtonEventArgs e
Returns
ありません
Author
Yuta Yoshinaga
Date
2017.10.20
Definition at line 421 of file SettingWindow.xaml.cs.
Referenced by ReversiWpf.SettingWindow.InitializeComponent().
pictureBoxPlayerColor1_MouseLeftButtonDown()
void ReversiWpf.SettingWindow.pictureBoxPlayerColor1_MouseLeftButtonDown (object sender, MouseButtonEventArgs e) private
プレイヤー1の色クリック
Parameters
[in] object sender
[in] MouseButtonEventArgs e
Returns
ありません
Author
Yuta Yoshinaga
Date
2017.10.20
Definition at line 346 of file SettingWindow.xaml.cs.
Referenced by ReversiWpf.SettingWindow.InitializeComponent().
pictureBoxPlayerColor2_MouseLeftButtonDown()
void ReversiWpf.SettingWindow.pictureBoxPlayerColor2_MouseLeftButtonDown (object sender, MouseButtonEventArgs e) private
プレイヤー2の色クリック
Parameters
[in] object sender
[in] MouseButtonEventArgs e
Returns
ありません
Author
Yuta Yoshinaga
Date
2017.10.20
Definition at line 371 of file SettingWindow.xaml.cs.
Referenced by ReversiWpf.SettingWindow.InitializeComponent().
reflectSettingForm()
void ReversiWpf.SettingWindow.reflectSettingForm () private
フォームに設定を反映
フォームから設定を読み込み
Returns
ありません
Author
Yuta Yoshinaga
Date
2017.10.20
Definition at line 76 of file SettingWindow.xaml.cs.
Referenced by ReversiWpf.SettingWindow.buttonDefault_Click(), and ReversiWpf.SettingWindow.SettingWindow().
The documentation for this class was generated from the following files:
obj/Debug/SettingWindow.g.cs
obj/Debug/SettingWindow.g.i.cs
SettingWindow.xaml.cs