ReversiWpf: ReversiWpf.MainWindow Class Reference
ReversiWpf.MainWindow Class Reference
MainWindow
Public Member Functions
static bool DeleteObject (IntPtr hObject)
gdi32.dllのDeleteObjectメソッドの使用を宣言する。
MainWindow ()
コンストラクタ
ImageSource ToImageSource (Bitmap bmp)
BITMAPかImageSourceに変換
ReversiSetting LoadSettingXml (string path)
設定XMLファイルロード
int SaveSettingXml (string path, ref ReversiSetting appSet)
設定XMLファイルセーブ
void appInit ()
アプリ初期化
void ViewMsgDlg (string title, string msg)
メッセージダイアログ
void ViewMsgDlgLocal (string title, string msg)
メッセージダイアログ
void DrawSingle (int y, int x, int sts, int bk, string text)
1マス描画
void DrawSingleLocal (int y, int x, int sts, int bk, string text)
1マス描画
void CurColMsg (string text)
現在の色メッセージ
void CurColMsgLocal (string text)
現在の色メッセージ
void CurStsMsg (string text)
現在のステータスメッセージ
void CurStsMsgLocal (string text)
現在のステータスメッセージ
void InitializeComponent ()
InitializeComponent
void InitializeComponent ()
InitializeComponent
void InitializeComponent ()
InitializeComponent
void InitializeComponent ()
InitializeComponent
Public Attributes
ReversiSetting m_AppSettings
アプリ設定
ReversiPlay m_ReversiPlay
リバーシ本体
Private Member Functions
delegate void ViewMsgDlgDelegate (string title, string msg)
delegate void DrawSingleDelegate (int y, int x, int sts, int bk, string text)
delegate void CurColMsgDelegate (string text)
delegate void CurStsMsgDelegate (string text)
delegate void Reversi_ResizeEndDelegate (object sender, EventArgs e)
void pictureBox_Click (object sender, MouseButtonEventArgs e)
マスクリック
void btn_reset_Click (object sender, RoutedEventArgs e)
リセットクリック
void btn_setting_Click (object sender, RoutedEventArgs e)
void System.Windows.Markup.IComponentConnector. Connect (int connectionId, object target)
void System.Windows.Markup.IComponentConnector. Connect (int connectionId, object target)
void System.Windows.Markup.IComponentConnector. Connect (int connectionId, object target)
void System.Windows.Markup.IComponentConnector. Connect (int connectionId, object target)
Private Attributes
System.Drawing.Size oldSize
リサイズ前のサイズ
bool _contentLoaded
Static Private Attributes
static System.Timers.Timer aTimer
タイマー
Detailed Description
MainWindow
MainWindow.xaml の相互作用ロジッククラス
Definition at line 46 of file MainWindow.xaml.cs.
Constructor & Destructor Documentation
MainWindow()
ReversiWpf.MainWindow.MainWindow ()
コンストラクタ
Returns
ありません
Author
Yuta Yoshinaga
Date
2017.10.20
Definition at line 70 of file MainWindow.xaml.cs.
Member Function Documentation
appInit()
void ReversiWpf.MainWindow.appInit ()
アプリ初期化
Returns
ありません
Author
Yuta Yoshinaga
Date
2017.10.20
Definition at line 197 of file MainWindow.xaml.cs.
Referenced by ReversiWpf.MainWindow.btn_reset_Click(), and ReversiWpf.MainWindow.MainWindow().
btn_reset_Click()
void ReversiWpf.MainWindow.btn_reset_Click (object sender, RoutedEventArgs e) private
リセットクリック
Parameters
[in] object sender
[in] RoutedEventArgs e
Returns
ありません
Author
Yuta Yoshinaga
Date
2017.10.20
Definition at line 517 of file MainWindow.xaml.cs.
Referenced by ReversiWpf.MainWindow.InitializeComponent().
CurColMsg()
void ReversiWpf.MainWindow.CurColMsg (string text)
現在の色メッセージ
Parameters
[in] string text テキスト
Returns
ありません
Author
Yuta Yoshinaga
Date
2017.10.20
Definition at line 437 of file MainWindow.xaml.cs.
Referenced by ReversiWpf.MainWindow.MainWindow().
CurColMsgLocal()
void ReversiWpf.MainWindow.CurColMsgLocal (string text)
現在の色メッセージ
Parameters
[in] string text テキスト
Returns
ありません
Author
Yuta Yoshinaga
Date
2017.10.20
Definition at line 451 of file MainWindow.xaml.cs.
Referenced by ReversiWpf.MainWindow.CurColMsg().
CurStsMsg()
void ReversiWpf.MainWindow.CurStsMsg (string text)
現在のステータスメッセージ
Parameters
[in] string text テキスト
Returns
ありません
Author
Yuta Yoshinaga
Date
2017.10.20
Definition at line 465 of file MainWindow.xaml.cs.
Referenced by ReversiWpf.MainWindow.MainWindow().
CurStsMsgLocal()
void ReversiWpf.MainWindow.CurStsMsgLocal (string text)
現在のステータスメッセージ
Parameters
[in] string text テキスト
Returns
ありません
Author
Yuta Yoshinaga
Date
2017.10.20
Definition at line 479 of file MainWindow.xaml.cs.
Referenced by ReversiWpf.MainWindow.CurStsMsg().
DrawSingle()
void ReversiWpf.MainWindow.DrawSingle (int y, int x, int sts, int bk, string text)
1マス描画
Parameters
[in] int y Y座標
[in] int x X座標
[in] int sts ステータス
[in] int bk 背景
[in] string text テキスト
Returns
ありません
Author
Yuta Yoshinaga
Date
2017.10.20
Definition at line 298 of file MainWindow.xaml.cs.
Referenced by ReversiWpf.MainWindow.MainWindow().
DrawSingleLocal()
void ReversiWpf.MainWindow.DrawSingleLocal (int y, int x, int sts, int bk, string text)
1マス描画
Parameters
[in] int y Y座標
[in] int x X座標
[in] int sts ステータス
[in] int bk 背景
[in] string text テキスト
Returns
ありません
Author
Yuta Yoshinaga
Date
2017.10.20
Definition at line 316 of file MainWindow.xaml.cs.
Referenced by ReversiWpf.MainWindow.DrawSingle().
InitializeComponent() [1/4]
void ReversiWpf.MainWindow.InitializeComponent ()
InitializeComponent
Definition at line 3290 of file MainWindow.g.cs.
Referenced by ReversiWpf.MainWindow.MainWindow().
InitializeComponent() [2/4]
void ReversiWpf.MainWindow.InitializeComponent ()
InitializeComponent
Definition at line 3290 of file MainWindow.g.i.cs.
InitializeComponent() [3/4]
void ReversiWpf.MainWindow.InitializeComponent ()
InitializeComponent
Definition at line 3290 of file MainWindow.g.cs.
InitializeComponent() [4/4]
void ReversiWpf.MainWindow.InitializeComponent ()
InitializeComponent
Definition at line 3290 of file MainWindow.g.i.cs.
LoadSettingXml()
ReversiSetting ReversiWpf.MainWindow.LoadSettingXml (string path)
設定XMLファイルロード
Parameters
[in] string path 設定XMLファイルパス
Returns
ReversiSettingオブジェクトインスタンス
Author
Yuta Yoshinaga
Date
2017.10.20
Definition at line 131 of file MainWindow.xaml.cs.
Referenced by ReversiWpf.MainWindow.MainWindow().
pictureBox_Click()
void ReversiWpf.MainWindow.pictureBox_Click (object sender, MouseButtonEventArgs e) private
マスクリック
Parameters
[in] object sender
[in] MouseButtonEventArgs e
Returns
ありません
Author
Yuta Yoshinaga
Date
2017.10.20
Definition at line 494 of file MainWindow.xaml.cs.
Referenced by ReversiWpf.MainWindow.InitializeComponent().
SaveSettingXml()
int ReversiWpf.MainWindow.SaveSettingXml (string path, ref ReversiSetting appSet)
設定XMLファイルセーブ
Parameters
[in] string path 設定XMLファイルパス
[out] ReversiSetting appSet 設定XMLファイルオブジェクト
Returns
0 : 成功 それ以外 : 失敗
Author
Yuta Yoshinaga
Date
2017.10.20
Definition at line 165 of file MainWindow.xaml.cs.
Referenced by ReversiWpf.MainWindow.btn_reset_Click(), and ReversiWpf.MainWindow.MainWindow().
ToImageSource()
ImageSource ReversiWpf.MainWindow.ToImageSource (Bitmap bmp)
BITMAPかImageSourceに変換
Parameters
[in] Bitmap bmp
Returns
ImageSource
Author
Yuta Yoshinaga
Date
2017.10.20
Definition at line 112 of file MainWindow.xaml.cs.
Referenced by ReversiWpf.MainWindow.DrawSingleLocal().
ViewMsgDlg()
void ReversiWpf.MainWindow.ViewMsgDlg (string title, string msg)
メッセージダイアログ
Parameters
[in] string title タイトル
[in] string msg メッセージ
Returns
ありません
Author
Yuta Yoshinaga
Date
2017.10.20
Definition at line 265 of file MainWindow.xaml.cs.
Referenced by ReversiWpf.MainWindow.MainWindow().
ViewMsgDlgLocal()
void ReversiWpf.MainWindow.ViewMsgDlgLocal (string title, string msg)
メッセージダイアログ
Parameters
[in] string title タイトル
[in] string msg メッセージ
Returns
ありません
Author
Yuta Yoshinaga
Date
2017.10.20
Definition at line 280 of file MainWindow.xaml.cs.
Referenced by ReversiWpf.MainWindow.ViewMsgDlg().
The documentation for this class was generated from the following files:
MainWindow.xaml.cs
obj/Debug/MainWindow.g.cs
obj/Debug/MainWindow.g.i.cs